"""column fix

Revision ID: c375ec08d682
Revises: e8349bc27188
Create Date: 2023-04-10 21:36:08.244214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c375ec08d682'
down_revision = 'e8349bc27188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))
        batch_op.drop_column('dificulty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dificulty', sa.INTEGER(), nullable=True))
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
